//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class conflict_dbo_data_residentFloor
    {
        public Nullable<int> C___originator_id { get; set; }
        public Nullable<int> C___origin_datasource { get; set; }
        public string C___tranid { get; set; }
        public Nullable<int> C___conflict_type { get; set; }
        public Nullable<bool> C___is_winner { get; set; }
        public byte[] C___pre_version { get; set; }
        public Nullable<int> C___reason_code { get; set; }
        public string C___reason_text { get; set; }
        public byte[] C___update_bitmap { get; set; }
        public System.DateTime C___inserted_date { get; set; }
        public byte[] C___row_id { get; set; }
        public byte[] C___change_id { get; set; }
        public Nullable<long> ID { get; set; }
        public string CommunityID { get; set; }
        public string FloorID { get; set; }
        public string FloorName { get; set; }
        public string CommunityFloorAdress { get; set; }
        public string FloorNumber { get; set; }
        public string RoomNumber { get; set; }
        public string DongName { get; set; }
        public string RoomName { get; set; }
        public string UnitNumber { get; set; }
        public string LayerNumber { get; set; }
        public string DirectDescription { get; set; }
        public string UnitCount { get; set; }
        public string WuYeSmallCategory { get; set; }
        public string HouseStruct { get; set; }
        public string BuildShape { get; set; }
        public string LandLayerCount { get; set; }
        public string UndergroundLayerCount { get; set; }
        public string MainDirect { get; set; }
        public string MinorDirect { get; set; }
        public string RoofStyle { get; set; }
        public string HouseNature { get; set; }
        public string HouseCount { get; set; }
        public string Ti { get; set; }
        public string TiHuBi { get; set; }
        public string IsHasLift { get; set; }
        public string LayerDifference { get; set; }
        public string LayerHigh { get; set; }
        public string Area { get; set; }
        public string DeFangPercent { get; set; }
        public string ZhuangXiuStandard { get; set; }
        public string ZhuangXiuUnitPrice { get; set; }
        public string ZhuangXiuDescription { get; set; }
        public string ParkCount { get; set; }
        public string FinishDate { get; set; }
        public string OuterWall { get; set; }
        public string WaterSupply { get; set; }
        public string SmartDevice { get; set; }
        public string InnerDevice { get; set; }
        public string AirConditionDevice { get; set; }
        public string CommonAirConditionBrand { get; set; }
        public string LiftBrand { get; set; }
        public string CenterAirConditionBrand { get; set; }
        public string LandScape { get; set; }
        public string GardenArea { get; set; }
        public string DataSrc { get; set; }
        public string DataStyle { get; set; }
        public string SurveyCompany { get; set; }
        public string Inquirer { get; set; }
        public string SurveyDate { get; set; }
        public string Verifier { get; set; }
        public string VerifyTime { get; set; }
        public string UpdatePerson { get; set; }
        public string UpdateTime { get; set; }
    }
}
