//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus_IsQuery
    {
        public long ID { get; set; }
        public Nullable<long> OrgnazationCode { get; set; }
        public Nullable<long> SearchArea { get; set; }
        public Nullable<long> SearchProperty { get; set; }
        public Nullable<long> UseTemplate { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool DefaultArea { get; set; }
        public bool LocalArea { get; set; }
        public bool Print { get; set; }
        public bool Stamp { get; set; }
        public long PrintPriceLimit { get; set; }
    }
}
