//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus_AreaDistribution
    {
        public long AreaID { get; set; }
        public Nullable<long> ProDictID { get; set; }
        public Nullable<long> CityDictID { get; set; }
        public Nullable<long> DisDictID { get; set; }
        public Nullable<long> DefaultCounty { get; set; }
        public Nullable<bool> IsSelect { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public Nullable<long> Com_ID { get; set; }
    }
}
