//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus_User
    {
        public long Us_ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Sex { get; set; }
        public string Area { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<long> UserGenre { get; set; }
        public Nullable<System.DateTime> EffectiveTime { get; set; }
        public Nullable<long> LoginStatus { get; set; }
        public string HD { get; set; }
        public string CPU { get; set; }
        public string MAC { get; set; }
        public string KEY { get; set; }
        public string IP { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Notice { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Unit { get; set; }
        public Nullable<long> Pt_ID { get; set; }
        public string Cellphone { get; set; }
        public string QQ { get; set; }
        public Nullable<System.DateTime> ApplicationTime { get; set; }
        public string LoginName { get; set; }
        public Nullable<long> Cmp_ID { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> Start { get; set; }
        public string PassWords { get; set; }
        public Nullable<long> Bra_ID { get; set; }
    }
}
