//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus_Role
    {
        public long RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<long> ROrder { get; set; }
        public long ComID { get; set; }
        public string Describe { get; set; }
        public string CreaterPerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
