//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus_Company
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> ProDictID { get; set; }
        public Nullable<long> CityDictID { get; set; }
        public Nullable<long> DisDictID { get; set; }
        public Nullable<long> Storey { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<long> RankID { get; set; }
        public Nullable<long> OrgID { get; set; }
    }
}
