//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_makePriceListMethod
    {
        public long ID { get; set; }
        public Nullable<long> TaskId { get; set; }
        public Nullable<long> MethodId { get; set; }
        public Nullable<decimal> MethodWeight { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<long> AssessState { get; set; }
        public Nullable<long> AssessPersonId { get; set; }
        public string AssessPersonName { get; set; }
        public Nullable<System.DateTime> AssessTime { get; set; }
        public Nullable<bool> CalcPrevious { get; set; }
        public Nullable<long> FloorMethodId { get; set; }
        public Nullable<long> RoomMethodId { get; set; }
        public string ErrorMsg { get; set; }
    }
}
