//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_officeProjectSummaryPrice
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string CountyCode { get; set; }
        public string RegionCode { get; set; }
        public string ProvinceCode { get; set; }
        public Nullable<long> PropertyTypeId { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<decimal> GrowthRate { get; set; }
        public string CurrentMonth { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatePerson { get; set; }
    }
}
