//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_officeFloor
    {
        public long ID { get; set; }
        public long ProjectId { get; set; }
        public string FloorId { get; set; }
        public string FloorName { get; set; }
        public string FloorAddress { get; set; }
        public string FloorNumber { get; set; }
        public string FloorType { get; set; }
        public string HouseStruct { get; set; }
        public string LouCengNumber { get; set; }
        public string MainUse { get; set; }
        public string SendUse { get; set; }
        public string CompleteDate { get; set; }
        public string PropertyLevel { get; set; }
        public string PropertyRightType { get; set; }
        public string BuildConstruct { get; set; }
        public string BuildStyle { get; set; }
        public string GetPercent { get; set; }
        public string MainDirect { get; set; }
        public string SecondDirect { get; set; }
        public string NearRoad { get; set; }
        public string LandUse { get; set; }
        public string LandArea { get; set; }
        public string LandNature { get; set; }
        public string LandEndDate { get; set; }
        public string GroundFloorCount { get; set; }
        public string UngroundFloorCount { get; set; }
        public string TotalBuildArea { get; set; }
        public string OfficeBuildArea { get; set; }
        public string StandardBuildArea { get; set; }
        public string StandardFloorHeight { get; set; }
        public string StandardFloorPureHeight { get; set; }
        public string MainArea { get; set; }
        public string AreaSescription { get; set; }
        public string RoofCondtion { get; set; }
        public string WuMianCondtion { get; set; }
        public string BuildNationFloorHeight { get; set; }
        public string VacancyFloorSelect { get; set; }
        public string VacancyFloorOther { get; set; }
        public string VacancyFloor { get; set; }
        public string VacancyFloorCount { get; set; }
        public string FloorState { get; set; }
        public string BuildDecorateArea { get; set; }
        public string Lobby { get; set; }
        public string LobbyHeight { get; set; }
        public string LobbyFront { get; set; }
        public string LobbyDecorate { get; set; }
        public string LobbyScale { get; set; }
        public string CorridorDecorate { get; set; }
        public string CorridorScale { get; set; }
        public string LiftDecorate { get; set; }
        public string LiftScale { get; set; }
        public string WcAllocation { get; set; }
        public string WcDecorate { get; set; }
        public string UnitWcFloorNumber { get; set; }
        public string FloorWcFloorNumber { get; set; }
        public string FocusWcFloorNumber { get; set; }
        public string LiftAllocation { get; set; }
        public string CustomerLiftBrand { get; set; }
        public string CustomerLiftCount { get; set; }
        public string GoodsLiftCount { get; set; }
        public string IsLiftPartition { get; set; }
        public string LowPartitionLiftCount { get; set; }
        public string MiddlePartitionLiftCount { get; set; }
        public string HeighPartitionCount { get; set; }
        public string SingleLiftCount { get; set; }
        public string DoubleLiftCount { get; set; }
        public string AllLiftCount { get; set; }
        public string AirConditionAllocation { get; set; }
        public string FocusAirFloorNum { get; set; }
        public string HalfFocusAirFloorNum { get; set; }
        public string FenTiAirFloorNum { get; set; }
        public string AirOpenWorkDay { get; set; }
        public string AirOpenSaturday { get; set; }
        public string airOpenSunday { get; set; }
        public string SecuritySystem { get; set; }
        public string ObjectiveFactor { get; set; }
        public string OpRiverDirect { get; set; }
        public string OpRiverFloorNum { get; set; }
        public string OpGreenDirect { get; set; }
        public string OpGreenFloorNum { get; set; }
        public string OpCityScape { get; set; }
        public string OpCityScapeFloorNum { get; set; }
        public string OpElevated { get; set; }
        public string OpElevatedFloorNum { get; set; }
        public string OpVoltage { get; set; }
        public string OpVoltageFloorNum { get; set; }
        public string PropertyCompany { get; set; }
        public string PropertyTel { get; set; }
        public string WuGuanForm { get; set; }
        public string WuGuanFee { get; set; }
        public string WuGuanFeeContain { get; set; }
        public string OuterBusiness { get; set; }
        public string EnableRegister { get; set; }
        public string IsSheWai { get; set; }
        public string Remark { get; set; }
        public string DataSrc { get; set; }
        public string DataStyle { get; set; }
        public string SurveyCompany { get; set; }
        public string Inquirer { get; set; }
        public string SurveyDate { get; set; }
        public string Verifier { get; set; }
        public string VerifyTime { get; set; }
        public string UpdatePerson { get; set; }
        public string UpdateTime { get; set; }
        public string PropertyType4 { get; set; }
        public string CountyCode { get; set; }
        public string RegionCode { get; set; }
        public string ProvinceCode { get; set; }
        public string FloorCode { get; set; }
        public string FloorUnit { get; set; }
        public string RoomUnit { get; set; }
        public string RoomNumber { get; set; }
        public string PropertyType { get; set; }
        public string RoomDistribute { get; set; }
        public string DirectInstruction { get; set; }
        public string DataState { get; set; }
        public string ProjectNameAddress { get; set; }
        public string HasLift { get; set; }
        public string BuildForUsing { get; set; }
        public string BuildRealUsing { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
