//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_residentProjectTemp
    {
        public long ID { get; set; }
        public string CommunityID { get; set; }
        public string CommunityName { get; set; }
        public string CommunityAlias { get; set; }
        public string CommunityAddress { get; set; }
        public string OtherAddress { get; set; }
        public string CommunityCode { get; set; }
        public string EastTo { get; set; }
        public string WestTo { get; set; }
        public string SouthTo { get; set; }
        public string NorthTo { get; set; }
        public string ProvinceCode { get; set; }
        public string RegionCode { get; set; }
        public string CountyCode { get; set; }
        public string StreetCode { get; set; }
        public string Community { get; set; }
        public string Module1Code { get; set; }
        public string Module1_1Code { get; set; }
        public string Loop { get; set; }
        public string TuQiuNO { get; set; }
        public string Zip { get; set; }
        public string CommunityType { get; set; }
        public string TimeOfCompletion { get; set; }
        public string DevelopersName { get; set; }
        public string ConstructionUnitName { get; set; }
        public string AgnetName { get; set; }
        public string SaleAddress { get; set; }
        public string SaleTel { get; set; }
        public string KaiPanTime { get; set; }
        public string ParkSituation { get; set; }
        public string GroundParkCount { get; set; }
        public string GroundParkFee { get; set; }
        public string UnderGroundParkCount { get; set; }
        public string UnderGroundParkFee { get; set; }
        public string BoWeiPercent { get; set; }
        public string GreenRate { get; set; }
        public string VolumeRate { get; set; }
        public string BulidDensity { get; set; }
        public string WuYeCompany { get; set; }
        public string WuYeFeeUnit { get; set; }
        public string MonetaryUnit { get; set; }
        public string WuYeFee { get; set; }
        public string WuYeFeeUpTo { get; set; }
        public string WuYeFeeLowTo { get; set; }
        public string LandArea { get; set; }
        public string TotalBuildArea { get; set; }
        public string ResidentialArea { get; set; }
        public string Households { get; set; }
        public string ProjectIntrodution { get; set; }
        public string ResidentialCount { get; set; }
        public string DeFangRate { get; set; }
        public string BuildType { get; set; }
        public string LandUseType { get; set; }
        public string LandStopDate { get; set; }
        public string LandLevel { get; set; }
        public string IsClosed { get; set; }
        public string BuildState { get; set; }
        public string CommunityMark { get; set; }
        public string CommunityGrade { get; set; }
        public string BuildStyle { get; set; }
        public string ClubProvideService { get; set; }
        public string SportsFacilities { get; set; }
        public string XiuXianFacilities { get; set; }
        public string InnerTrafic { get; set; }
        public string CommunityInfra { get; set; }
        public string BusStationDistance { get; set; }
        public string BusLineCount { get; set; }
        public string BusLinesName { get; set; }
        public string BusRapidTransit { get; set; }
        public string SubwayDistance { get; set; }
        public string SubwayNames { get; set; }
        public string TraficAround { get; set; }
        public string SupportingFacilities { get; set; }
        public string FacilitiesAround { get; set; }
        public string AirPollution { get; set; }
        public string NoisePollution { get; set; }
        public string OtherPollution { get; set; }
        public string OtherImpact { get; set; }
        public string VegetableMarket { get; set; }
        public string LargeMarket { get; set; }
        public string FinancialInstit { get; set; }
        public string WenTiChangGuan { get; set; }
        public string AdministrativeOffice { get; set; }
        public string Kindergarten { get; set; }
        public string ToPrimarySchoolName { get; set; }
        public string ToHighSchoolName { get; set; }
        public string University { get; set; }
        public string Hostipal { get; set; }
        public string DataSrc { get; set; }
        public string DataType { get; set; }
        public string SurveyUnit { get; set; }
        public string Investigator { get; set; }
        public string SurveyTime { get; set; }
        public string ReviewPerson { get; set; }
        public string ReviewTime { get; set; }
        public string UpdatePerson { get; set; }
        public string UpdateTime { get; set; }
        public string PropertyFeeDescription { get; set; }
        public string FloorCountDescription { get; set; }
        public string ProjectLevel { get; set; }
        public string GetInDate { get; set; }
        public string ProjectAround { get; set; }
        public string ProjectRemark { get; set; }
        public string LandUsing { get; set; }
        public string LandRightType { get; set; }
        public string PrimarySchool { get; set; }
        public string MiddleSchool { get; set; }
        public string SubwayCount { get; set; }
        public string PrimarySchoolHot { get; set; }
        public string SchoolHousingRemark { get; set; }
        public string Status { get; set; }
        public string DetachedGarageCount { get; set; }
        public string FloorRemark { get; set; }
        public string DesignCompany { get; set; }
        public string bustlingDegree { get; set; }
        public string projectMaturity { get; set; }
        public string projectScale { get; set; }
        public string environment { get; set; }
        public string landscape { get; set; }
        public string rangeToCenter { get; set; }
        public string businessDistrict { get; set; }
        public string ProjectID { get; set; }
        public string sideSchool { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> TempStatus { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> Submit { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<long> ProjectUpdateId { get; set; }
    }
}
