//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_residentProjectSummaryPrice
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public long CountyCode { get; set; }
        public long RegionCode { get; set; }
        public long ProvinceCode { get; set; }
        public long PropertyTypeId { get; set; }
        public decimal AvgPrice { get; set; }
        public decimal GrowthRate { get; set; }
        public int CurrentMonth { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatePerson { get; set; }
    }
}
