//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_attachment
    {
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string ModuleKey { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> PictureType { get; set; }
        public string FileType { get; set; }
        public double FileSize { get; set; }
        public string MD5 { get; set; }
        public string CreatePerson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Seq { get; set; }
    }
}
