//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_uploadDirectory
    {
        public long id { get; set; }
        public long ObjectId { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> ProduceDirState { get; set; }
        public Nullable<int> WriteState { get; set; }
        public string BaseDirPath { get; set; }
        public Nullable<long> CreatePersonId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePersonName { get; set; }
        public Nullable<long> CreateOrgId { get; set; }
        public string CreateOrgName { get; set; }
    }
}
