//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_residentTradeCase
    {
        public long CaseID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Street { get; set; }
        public string Community { get; set; }
        public string Plate1 { get; set; }
        public string Plate1_1 { get; set; }
        public string CaseAddress { get; set; }
        public string BelongSmallRegion { get; set; }
        public string BelongFloor { get; set; }
        public string FloorNum { get; set; }
        public string RoomNum { get; set; }
        public string GroundFloorCount { get; set; }
        public string FloorOf { get; set; }
        public string ResidentCategory { get; set; }
        public string Seller { get; set; }
        public string SellerTel { get; set; }
        public string Buyer { get; set; }
        public string BuyerTel { get; set; }
        public Nullable<double> BuildArea { get; set; }
        public Nullable<double> ResidentArea { get; set; }
        public Nullable<double> YueCengArea { get; set; }
        public Nullable<double> BikeLibraryArea { get; set; }
        public Nullable<double> CarLibraryArea { get; set; }
        public Nullable<System.DateTime> ListTime { get; set; }
        public Nullable<double> StartPrice { get; set; }
        public Nullable<System.DateTime> BargainTime { get; set; }
        public Nullable<double> BargainTotalPrice { get; set; }
        public Nullable<double> BargainSinglePrice { get; set; }
        public string BargainState { get; set; }
        public Nullable<bool> IsSellerNetPrice { get; set; }
        public string PriceNeiHan { get; set; }
        public string PayWay { get; set; }
        public Nullable<bool> IsOverTwoYears { get; set; }
        public Nullable<bool> IsUniqueHouse { get; set; }
        public string DecorateCondition { get; set; }
        public Nullable<System.DateTime> DecorateTime { get; set; }
        public string FacilityCondition { get; set; }
        public string HouseDirect { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
