//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_officeProject
    {
        public long ID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectOtherName { get; set; }
        public string ProjectAddress { get; set; }
        public string OtherAddress { get; set; }
        public string EastTo { get; set; }
        public string SouthTo { get; set; }
        public string WestTo { get; set; }
        public string NorthTo { get; set; }
        public string ProjectType { get; set; }
        public string ProvinceCode { get; set; }
        public string RegionCode { get; set; }
        public string CountyCode { get; set; }
        public string Plate { get; set; }
        public string Plate1_1 { get; set; }
        public string BusinessCircle { get; set; }
        public string Loop { get; set; }
        public string TuQiuCode { get; set; }
        public string Zip { get; set; }
        public string Developers { get; set; }
        public string Investors { get; set; }
        public string ConstructionUnit { get; set; }
        public string BuildDesign { get; set; }
        public string ObjectiveDesign { get; set; }
        public string SaleAgent { get; set; }
        public string SaleAddress { get; set; }
        public string SaleTel { get; set; }
        public string RentAgent { get; set; }
        public string RentAddress { get; set; }
        public string RentTel { get; set; }
        public string OpenDate { get; set; }
        public string CompleteDate { get; set; }
        public string LandArea { get; set; }
        public string TotalBuildArea { get; set; }
        public string OfficeArea { get; set; }
        public string VolumeRate { get; set; }
        public string GreenRate { get; set; }
        public string BulidDensity { get; set; }
        public string ParkSituation { get; set; }
        public string GroundParkCount { get; set; }
        public string UngroundParkCount { get; set; }
        public string GroundParkFee { get; set; }
        public string UngroundParkFee { get; set; }
        public string TempParkFee { get; set; }
        public string ParkPercent { get; set; }
        public string PropertyCompany { get; set; }
        public string PropertyPayCompany { get; set; }
        public string MoneyUnit { get; set; }
        public string PropertyFee { get; set; }
        public string PropertyFeeRemark { get; set; }
        public string PropertyFeeMax { get; set; }
        public string PropertyFeeMin { get; set; }
        public string ProjectState { get; set; }
        public string LandUseType { get; set; }
        public string LandEndDate { get; set; }
        public string LandLevel { get; set; }
        public string BuildType { get; set; }
        public string OfficeLevel { get; set; }
        public string IsClose { get; set; }
        public string BuildStyle { get; set; }
        public string SupportingFacilities { get; set; }
        public string ProjectFloorCount { get; set; }
        public string PureOfficeFloorCount { get; set; }
        public string HotelFloorCount { get; set; }
        public string ResidentialFloorCount { get; set; }
        public string OfficeHouseFloorCount { get; set; }
        public string ServicedApartments { get; set; }
        public string Business { get; set; }
        public string BusinessAround { get; set; }
        public string FoodAround { get; set; }
        public string BankAround { get; set; }
        public string HotelAround { get; set; }
        public string SubwayLines { get; set; }
        public string BusLines { get; set; }
        public string FastTrack { get; set; }
        public string AdministrativeOrgan { get; set; }
        public string TouristAttractions { get; set; }
        public string DataSrc { get; set; }
        public string DataStyle { get; set; }
        public string SurveyCompany { get; set; }
        public string Inquirer { get; set; }
        public string SurveyDate { get; set; }
        public string Verifier { get; set; }
        public string VerifyTime { get; set; }
        public string UpdatePerson { get; set; }
        public string UpdateTime { get; set; }
        public string ProjectCode { get; set; }
        public string Street_County { get; set; }
        public string Community_Village { get; set; }
        public string LandUse { get; set; }
        public string DetachedGarageCount { get; set; }
        public string FloorRemark { get; set; }
        public string DesignCompany { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
