//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_MakePriceSubmitLog
    {
        public long ID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleKey { get; set; }
        public string SubmitToRole { get; set; }
        public string SubmitToPerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Content { get; set; }
        public string Opinion { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> PriceDate { get; set; }
    }
}
