//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_makePriceList
    {
        public long ID { get; set; }
        public string Number { get; set; }
        public string TaskName { get; set; }
        public string PropertyTypeIds { get; set; }
        public string PropertyTypeNames { get; set; }
        public Nullable<long> MakePriceTypeId { get; set; }
        public string MakePriceTypeName { get; set; }
        public Nullable<System.DateTime> AssessPriceTime { get; set; }
        public Nullable<System.DateTime> OverTime { get; set; }
        public Nullable<long> PriceType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string TaskRemarks { get; set; }
        public string Opinion { get; set; }
        public Nullable<bool> IsSendSms { get; set; }
        public Nullable<bool> IsSendMail { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<long> TaskState { get; set; }
        public Nullable<long> CancelState { get; set; }
        public Nullable<long> CreatePersonId { get; set; }
        public string FlowId { get; set; }
        public string FlowInstanceId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> RealEndTime { get; set; }
    }
}
