//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_OfficeBuildingsCase
    {
        public long ID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public Nullable<long> BuildingID { get; set; }
        public string Building { get; set; }
        public string Address { get; set; }
        public Nullable<long> FloorBuildingID { get; set; }
        public string FloorBuilding { get; set; }
        public Nullable<long> RoomCode { get; set; }
        public string Room { get; set; }
        public string HousingStructure { get; set; }
        public string HousingDetail { get; set; }
        public string Sellers { get; set; }
        public string SellersTel { get; set; }
        public string BuyingParty { get; set; }
        public string BuyingPartyTel { get; set; }
        public Nullable<decimal> ListedTotlePrice { get; set; }
        public Nullable<decimal> ListedPrice { get; set; }
        public Nullable<System.DateTime> ListedTime { get; set; }
        public Nullable<decimal> TradingPrice { get; set; }
        public Nullable<decimal> TradingUnitPrice { get; set; }
        public Nullable<System.DateTime> TradingTime { get; set; }
        public string PriceIntention { get; set; }
        public string PaymentTerms { get; set; }
        public string TradingConditions { get; set; }
        public string DecorateSituation { get; set; }
        public string SupportingFacilities { get; set; }
        public string Remark { get; set; }
        public string HouseCertificate { get; set; }
        public string AuthorityCardName { get; set; }
        public string AuthorityCardNum { get; set; }
        public string PropertyRightsMan { get; set; }
        public string PropertyRightsType { get; set; }
        public string BuildingStructure { get; set; }
        public Nullable<decimal> FloorArea { get; set; }
        public Nullable<decimal> OtherArea { get; set; }
        public string UpperFloorNum { get; set; }
        public string DownFloorNum { get; set; }
        public string FloorNum { get; set; }
        public string DoorModel { get; set; }
        public string BuildDate { get; set; }
        public string Toward { get; set; }
        public string EdgeRoom { get; set; }
        public string DecorationStandard { get; set; }
        public Nullable<System.DateTime> DecorationTime { get; set; }
        public string MaintenanceSituation { get; set; }
        public string Landscape { get; set; }
        public string BuildingType { get; set; }
        public string ReservedFactors1 { get; set; }
        public string ReservedFactors2 { get; set; }
        public string ReservedFactors3 { get; set; }
        public string LandAuthorityCardName { get; set; }
        public string LandAuthorityCardNum { get; set; }
        public string LandPropertyRightsMan { get; set; }
        public string LandType { get; set; }
        public string LandStatus { get; set; }
        public string LandUseTypes { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string LandArea { get; set; }
        public string ContractCertificateNum { get; set; }
        public Nullable<System.DateTime> TakeCredentialsDate { get; set; }
        public string UnderPartyName { get; set; }
        public string UnderMutualPerson { get; set; }
        public string EvaluatedPrice { get; set; }
        public string TransactionType { get; set; }
        public string HousingLandLocated { get; set; }
        public string TaxPrice { get; set; }
        public string TaxArea { get; set; }
        public string InsideSpaceArea { get; set; }
        public string PropertyArea { get; set; }
        public string TransferArea { get; set; }
        public string TransferAreaMainRoom { get; set; }
        public string TransferAreaAttachedRoom { get; set; }
        public Nullable<System.DateTime> TaxOperationDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string CaseType { get; set; }
        public string GetWay { get; set; }
        public string SourceTitle { get; set; }
        public string HouseMessageType { get; set; }
        public string ReleaseMan { get; set; }
        public string RelManTel { get; set; }
        public string CollectUrl { get; set; }
        public string SourceCaseNum { get; set; }
        public string ImgName { get; set; }
        public string CollectMan { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
        public string DataImportMan { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string UpdateMan { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
