//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_officeRoom
    {
        public long ID { get; set; }
        public string RoomSystemAddress { get; set; }
        public string RoomRightAddress { get; set; }
        public long BelongProject { get; set; }
        public long BelongFloor { get; set; }
        public string RoomID { get; set; }
        public string PropertyCategory { get; set; }
        public string BuildArea { get; set; }
        public string InnerArea { get; set; }
        public string ShareArea { get; set; }
        public string RealLayer { get; set; }
        public string NominalLayer { get; set; }
        public string HouseStruct { get; set; }
        public string LayerHigh { get; set; }
        public string PureHigh { get; set; }
        public string MainDirect { get; set; }
        public string MinorDirect { get; set; }
        public string RoomEvaluation { get; set; }
        public string PilarAffectEvaluation { get; set; }
        public string HasUpDownWater { get; set; }
        public string ObjectiveFactor { get; set; }
        public string Remark { get; set; }
        public string DataSrc { get; set; }
        public string DataStyle { get; set; }
        public string SurveyCompany { get; set; }
        public string Inquirer { get; set; }
        public string SurveyDate { get; set; }
        public string Verifier { get; set; }
        public string VerifyTime { get; set; }
        public string UpdatePerson { get; set; }
        public string UpdateTime { get; set; }
        public string PropertyType4 { get; set; }
        public string ProvinceCode { get; set; }
        public string RegionCode { get; set; }
        public string CountyCode { get; set; }
        public string CompletionYear { get; set; }
        public string ProjectId { get; set; }
        public string FloorId { get; set; }
        public string RoomCode { get; set; }
        public string FloorNumber { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
