//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_baseInfoGroupFields
    {
        public long ID { get; set; }
        public Nullable<long> FieldID { get; set; }
        public Nullable<long> FieldIndex { get; set; }
        public Nullable<bool> IsChoose { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<bool> IsFill { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string GroupContact { get; set; }
        public Nullable<long> FieldLength { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsWhere { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string FieldValue { get; set; }
        public Nullable<long> FieldValueLevel { get; set; }
        public Nullable<bool> IsMerge { get; set; }
        public Nullable<bool> IsShowInForm { get; set; }
        public Nullable<bool> IsShowInViss { get; set; }
        public string AreaIds { get; set; }
    }
}
