//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_pictureType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DictType { get; set; }
        public string RangeType { get; set; }
        public Nullable<int> Seq { get; set; }
        public string CreatePerson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public string FileType { get; set; }
        public Nullable<bool> ShowInViss { get; set; }
    }
}
