//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_residentRoom
    {
        public long ID { get; set; }
        public string RoomSystemAddress { get; set; }
        public string RoomRightAddress { get; set; }
        public long CommunityID { get; set; }
        public long FloorID { get; set; }
        public string WuYeCategory { get; set; }
        public string UnitNumber { get; set; }
        public string RoomNumber { get; set; }
        public string MainDirect { get; set; }
        public string MinorDirect { get; set; }
        public string BuildArea { get; set; }
        public string InnerArea { get; set; }
        public string ShareArea { get; set; }
        public string Layer1 { get; set; }
        public string Layer2 { get; set; }
        public string CompleteDate { get; set; }
        public string DecorateYear { get; set; }
        public string LandscapeSrc { get; set; }
        public string NominalLayer { get; set; }
        public string HouseStruct { get; set; }
        public string RoomStyle { get; set; }
        public string LayerHigh { get; set; }
        public string PureHigh { get; set; }
        public string TianJing { get; set; }
        public string Garden { get; set; }
        public string BaseMent { get; set; }
        public string ZhuangXiuStandard { get; set; }
        public string Terrace { get; set; }
        public string DataSrc { get; set; }
        public string DataStyle { get; set; }
        public string SurveyCompany { get; set; }
        public string Inquirer { get; set; }
        public string SurveyDate { get; set; }
        public string Verifier { get; set; }
        public string VerifyTime { get; set; }
        public string UpdatePerson { get; set; }
        public string UpdateTime { get; set; }
        public string PropertyType4 { get; set; }
        public string ProvinceCode { get; set; }
        public string RegionCode { get; set; }
        public string CountyCode { get; set; }
        public string RoomId { get; set; }
        public string RoomCode { get; set; }
        public string ResidenceNameAddress { get; set; }
        public string FloorNameAddress { get; set; }
        public string BedRoom { get; set; }
        public string LivingRoom { get; set; }
        public string WashRoom { get; set; }
        public string Balcony { get; set; }
        public string InternalFacilities { get; set; }
        public string HouseNature { get; set; }
        public string ApartmentStructure { get; set; }
        public string CategoryOfRights { get; set; }
        public string ZhuangXiuUnitPrice { get; set; }
        public string RealLayer { get; set; }
        public string IsHasLift { get; set; }
        public string ForecastContructionArea { get; set; }
        public string ForecastIndoorArea { get; set; }
        public string ForecastshareArea { get; set; }
        public string ForecastundergroundArea { get; set; }
        public string ForecastOtherArea { get; set; }
        public string ForecastShareModulus { get; set; }
        public string ActualundergroundArea { get; set; }
        public string ActualOtherArea { get; set; }
        public string ActualShareModulus { get; set; }
        public string LandArea { get; set; }
        public string ShareLandArea { get; set; }
        public string OwnLandArea { get; set; }
        public string RoomPicID { get; set; }
        public string isStandard { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Flag { get; set; }
        public string buildPlanUse { get; set; }
        public string buildPracticalUse { get; set; }
        public string roomDescription { get; set; }
        public string useStatus { get; set; }
        public string roomCount { get; set; }
        public string ProjectID { get; set; }
        public string UnitID { get; set; }
        public string Room1ID { get; set; }
        public string towards1 { get; set; }
        public string towards2 { get; set; }
        public string towards3 { get; set; }
        public string towards4 { get; set; }
        public string towards5 { get; set; }
    }
}
