//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_NewsBulletinInfo
    {
        public long NewsID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<long> NewsType { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public string PlatformObject { get; set; }
        public string ClientObject { get; set; }
        public string NewsContent { get; set; }
        public Nullable<long> BrowseQuantity { get; set; }
        public string NewsContentPuth { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> UserId { get; set; }
        public string ReleaseOrg { get; set; }
    }
}
