//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_baseInfoAllFields
    {
        public long ID { get; set; }
        public string GroupContact { get; set; }
        public string FieldNameCn { get; set; }
        public string FieldNameEn { get; set; }
        public string FieldType { get; set; }
        public string FieldConstraint { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsInGroup { get; set; }
    }
}
