//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_originatorid_history
    {
        public string originator_publication { get; set; }
        public int originator_id { get; set; }
        public string originator_node { get; set; }
        public string originator_db { get; set; }
        public int originator_db_version { get; set; }
        public int originator_version { get; set; }
        public System.DateTime inserted_date { get; set; }
    }
}
