//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_topologyresponse
    {
        public Nullable<int> request_id { get; set; }
        public string peer { get; set; }
        public Nullable<int> peer_version { get; set; }
        public string peer_db { get; set; }
        public Nullable<int> originator_id { get; set; }
        public Nullable<int> peer_conflict_retention { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string connection_info { get; set; }
    }
}
