//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_conflictdetectionconfigresponse
    {
        public int request_id { get; set; }
        public string peer_node { get; set; }
        public string peer_db { get; set; }
        public Nullable<int> peer_version { get; set; }
        public Nullable<int> peer_db_version { get; set; }
        public Nullable<bool> is_peer { get; set; }
        public Nullable<bool> conflictdetection_enabled { get; set; }
        public Nullable<int> originator_id { get; set; }
        public Nullable<int> peer_conflict_retention { get; set; }
        public Nullable<bool> peer_continue_onconflict { get; set; }
        public string peer_subscriptions { get; set; }
        public string progress_phase { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
