//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_menu
    {
        public string MenuCode { get; set; }
        public string ParentCode { get; set; }
        public string MenuName { get; set; }
        public string FuncCode { get; set; }
        public string IconClass { get; set; }
        public string IconURL { get; set; }
        public string MenuSeq { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> OpenMode { get; set; }
        public string AppID { get; set; }
        public string URL { get; set; }
        public string ParamInfo { get; set; }
    }
}
