//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_plateInfo
    {
        public long Pid { get; set; }
        public string PlateName { get; set; }
        public string PlateCode { get; set; }
        public string ToEast { get; set; }
        public string ToWest { get; set; }
        public string ToSouth { get; set; }
        public string ToNorth { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PlateParentCode { get; set; }
        public string StreetName { get; set; }
        public string StreetCode { get; set; }
        public string CommunityName { get; set; }
        public string CommunityCode { get; set; }
        public string HigherCode { get; set; }
        public Nullable<int> Ptype { get; set; }
        public Nullable<long> PFid { get; set; }
        public string PDistrict { get; set; }
    }
}
