//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_MakePriceQuery
    {
        public int ID { get; set; }
        public long AreaId { get; set; }
        public long PropertyId { get; set; }
        public string PropertyTypeCode { get; set; }
        public long ProjectId { get; set; }
        public long FloorId { get; set; }
        public long RoomId { get; set; }
        public int SettingType { get; set; }
        public int QueryType { get; set; }
        public int MethodId { get; set; }
        public string ParamsStr { get; set; }
        public string PropertyTypesStr { get; set; }
        public string MakePriceUser { get; set; }
        public System.DateTime MakePriceDate { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string MakePriceLog { get; set; }
        public string AssessmentPrice { get; set; }
    }
}
