//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_ParameterValue
    {
        public sys_ParameterValue()
        {
            this.sys_ParameterConditionValue = new HashSet<sys_ParameterConditionValue>();
        }
    
        public int ID { get; set; }
        public int ParamSettingID { get; set; }
        public string Value { get; set; }
        public string SelDictTypeID { get; set; }
        public string SelDictTypeName { get; set; }
        public Nullable<int> SelDictID { get; set; }
        public string SelDictText { get; set; }
        public string InputKey { get; set; }
        public string InputValue { get; set; }
        public Nullable<decimal> UpperValue { get; set; }
        public Nullable<decimal> LowerValue { get; set; }
        public bool IncludeUpper { get; set; }
        public bool IncludeLower { get; set; }
        public decimal Coefficient { get; set; }
        public Nullable<System.DateTime> EnableDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string ForPropertyCode { get; set; }
        public string ForPropertyName { get; set; }
        public bool IsDel { get; set; }
        public Nullable<decimal> UpFloat { get; set; }
        public Nullable<decimal> DownFloat { get; set; }
        public Nullable<int> SelDictID2 { get; set; }
        public string SelDictText2 { get; set; }
        public string SelDictTypeID2 { get; set; }
        public string SelDictTypeName2 { get; set; }
        public string ConditionValueStr { get; set; }
    
        public virtual ICollection<sys_ParameterConditionValue> sys_ParameterConditionValue { get; set; }
    }
}
