//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_application
    {
        public long AppID { get; set; }
        public string AppCode { get; set; }
        public string AppName { get; set; }
        public Nullable<int> IsOpen { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string Url { get; set; }
        public string AppDesc { get; set; }
        public string ManRole { get; set; }
        public string IpAdr { get; set; }
        public string IpPort { get; set; }
        public string AppKey { get; set; }
    }
}
