//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Tax
    {
        public int Id { get; set; }
        public long TaxSetting { get; set; }
        public long AreaId { get; set; }
        public long SellerType { get; set; }
        public long HousingType { get; set; }
        public Nullable<long> OriginalProof { get; set; }
        public Nullable<long> IsTheOnly { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public Nullable<int> AreaLimit { get; set; }
        public Nullable<int> PriceLimit { get; set; }
        public Nullable<long> Address { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string Expression { get; set; }
        public string Content { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string SellerTypeName { get; set; }
        public string HousingTypeName { get; set; }
        public string OriginalProofName { get; set; }
        public string IsTheOnlyName { get; set; }
        public string AddressName { get; set; }
        public string AgeSign { get; set; }
        public string AreaSign { get; set; }
        public string PriceSign { get; set; }
        public Nullable<int> CostType { get; set; }
        public string CostTypeName { get; set; }
        public Nullable<int> Assume { get; set; }
        public string AssumeName { get; set; }
    }
}
