//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_dictOrganize
    {
        public long ID { get; set; }
        public Nullable<long> DictID { get; set; }
        public string DictType { get; set; }
        public Nullable<long> OrganizeId { get; set; }
    }
}
