//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_MethodTitle
    {
        public int ID { get; set; }
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public int SettingType { get; set; }
        public string SettingTypeName { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
