//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_UsageLog
    {
        public long LogID { get; set; }
        public string LogContent { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string CreatePersonnel { get; set; }
        public Nullable<long> AppID { get; set; }
    }
}
