//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_employee
    {
        public long EmpID { get; set; }
        public string EmpCode { get; set; }
        public string UserID { get; set; }
        public string EmpName { get; set; }
        public string OrgList { get; set; }
        public long OrgID { get; set; }
        public Nullable<long> Position { get; set; }
        public string RealName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string EmpStatus { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OTel { get; set; }
        public string OEmail { get; set; }
        public string MobleNo { get; set; }
        public string Ddgree { get; set; }
        public string Specialty { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastModyDate { get; set; }
    }
}
