//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_CAADMethod
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool CaseStandard { get; set; }
        public bool MakePriceBat { get; set; }
        public bool MakePriceFront { get; set; }
        public bool CreatePrice { get; set; }
        public bool UpdatePirce { get; set; }
        public int PriceType { get; set; }
        public string PriceTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
