//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_jobs
    {
        public long JobID { get; set; }
        public string JobName { get; set; }
        public string JobResponsibility { get; set; }
        public string OrganizaCode { get; set; }
        public string OrganizaID { get; set; }
        public Nullable<int> JobStatus { get; set; }
    }
}
