//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_organize_bak
    {
        public long ID { get; set; }
        public string OrganizeCode { get; set; }
        public Nullable<long> ParentCode { get; set; }
        public Nullable<int> OrganizeSeq { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<int> OrgClasses { get; set; }
        public string OrganizeFullName { get; set; }
        public Nullable<int> OrgType { get; set; }
        public string Description { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
