//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Parameter
    {
        public sys_Parameter()
        {
            this.sys_ParameterCondition = new HashSet<sys_ParameterCondition>();
        }
    
        public int ID { get; set; }
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int ValueType { get; set; }
        public int CalculateType { get; set; }
        public bool IsEnable { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ForProperty { get; set; }
        public Nullable<bool> MultiSelect { get; set; }
        public string Value1Name { get; set; }
        public string Value2Name { get; set; }
        public decimal PWeight { get; set; }
        public decimal Ratio { get; set; }
        public string Expression { get; set; }
        public Nullable<int> Source { get; set; }
        public string FieldCode { get; set; }
        public string AssessmentField { get; set; }
        public Nullable<int> UseDictID { get; set; }
        public bool IsDel { get; set; }
        public bool CaseStandard { get; set; }
        public bool MakePriceBat { get; set; }
        public bool MakePriceFront { get; set; }
        public string SelDictTypeID { get; set; }
        public bool SealCase { get; set; }
        public bool LeaseCase { get; set; }
        public bool ProjectBat { get; set; }
        public bool FloorBat { get; set; }
        public bool RoomBat { get; set; }
        public string VISSExpression { get; set; }
        public string SealCaseExpression { get; set; }
        public string LeaseCaseExpression { get; set; }
        public string ProjectBatExpression { get; set; }
        public string FloorBatExpression { get; set; }
        public string RoomBatExpression { get; set; }
        public string SelDictTypeID2 { get; set; }
        public string SelDictTypeName2 { get; set; }
        public string SelDictTypeText2 { get; set; }
    
        public virtual ICollection<sys_ParameterCondition> sys_ParameterCondition { get; set; }
    }
}
