//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_propertyTypeCondition
    {
        public long Id { get; set; }
        public Nullable<int> AreaType { get; set; }
        public Nullable<long> AreaID { get; set; }
        public Nullable<long> PropertyTypeID { get; set; }
        public string PropertyTypeName { get; set; }
        public Nullable<long> CorrectionFactor { get; set; }
        public string CorrectionFactorName { get; set; }
        public string ConditionCode { get; set; }
        public string ConditionName { get; set; }
        public string ValueType { get; set; }
        public Nullable<int> IsInput { get; set; }
        public string SelectItem { get; set; }
        public Nullable<long> Creator { get; set; }
        public string CreatorName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> IsCorrectionCoefficient { get; set; }
        public Nullable<int> IsVisble { get; set; }
    }
}
