//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_MakePriceTemplate
    {
        public int ID { get; set; }
        public Nullable<long> OrganizeID { get; set; }
        public string OrganizeName { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public string PropertyName { get; set; }
        public Nullable<long> TemplateTypeID { get; set; }
        public string TemplateTypeName { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool UserImage { get; set; }
        public bool PreviewImage { get; set; }
        public bool StampImage { get; set; }
    }
}
