//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_propertyPlateCollects
    {
        public long ID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string CollectName { get; set; }
        public string Collects { get; set; }
        public string CollectsNames { get; set; }
        public Nullable<long> seq { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
