//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssubscriptions
    {
        public int artid { get; set; }
        public short srvid { get; set; }
        public string dest_db { get; set; }
        public byte status { get; set; }
        public byte sync_type { get; set; }
        public string login_name { get; set; }
        public int subscription_type { get; set; }
        public byte[] distribution_jobid { get; set; }
        public byte[] timestamp { get; set; }
        public byte update_mode { get; set; }
        public bool loopback_detection { get; set; }
        public bool queued_reinit { get; set; }
        public byte nosync_type { get; set; }
        public string srvname { get; set; }
    }
}
