//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class systranschemas
    {
        public int tabid { get; set; }
        public byte[] startlsn { get; set; }
        public byte[] endlsn { get; set; }
        public int typeid { get; set; }
    }
}
